In [36]:
import numpy as np
import pandas as pd

In [37]:
data = np.random.randint(low=0, high=6, size=(5, 10))

In [38]:
print(data)

[[4 3 5 5 3 4 1 3 1 3]
 [1 2 5 2 2 3 3 2 2 0]
 [0 4 1 5 4 0 3 2 0 0]
 [0 4 3 1 0 1 2 0 5 4]
 [1 4 0 5 4 4 1 2 0 3]]


In [39]:
df = pd.DataFrame(data=data)

In [40]:
df

0  1  2  3  4  5  6  7  8  9
0  4  3  5  5  3  4  1  3  1  3
1  1  2  5  2  2  3  3  2  2  0
2  0  4  1  5  4  0  3  2  0  0
3  0  4  3  1  0  1  2  0  5  4
4  1  4  0  5  4  4  1  2  0  3